# TCL File Generated by Component Editor 12.1sp1
# Fri Feb 27 18:09:39 MST 2015
# DO NOT MODIFY


# 
# WHY "WHY" v1.0
# null 2015.02.27.18:09:39
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module WHY
# 
set_module_property NAME WHY
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME WHY
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WaveformGenerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file WHY.vhd VHDL PATH ourVHDL/WHY.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point waveform_right
# 
add_interface waveform_right avalon_streaming end
set_interface_property waveform_right associatedClock clock_sink
set_interface_property waveform_right associatedReset reset
set_interface_property waveform_right dataBitsPerSymbol 8
set_interface_property waveform_right errorDescriptor ""
set_interface_property waveform_right firstSymbolInHighOrderBits true
set_interface_property waveform_right maxChannel 0
set_interface_property waveform_right readyLatency 0
set_interface_property waveform_right ENABLED true

add_interface_port waveform_right asi_data_waveform_right data Input 16
add_interface_port waveform_right asi_valid_waveform_right valid Input 1
add_interface_port waveform_right asi_ready_waveform_right ready Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink csi_clk50 clk Input 1


# 
# connection point waveform_right1
# 
add_interface waveform_right1 avalon_streaming end
set_interface_property waveform_right1 associatedClock clock_sink
set_interface_property waveform_right1 associatedReset reset
set_interface_property waveform_right1 dataBitsPerSymbol 8
set_interface_property waveform_right1 errorDescriptor ""
set_interface_property waveform_right1 firstSymbolInHighOrderBits true
set_interface_property waveform_right1 maxChannel 0
set_interface_property waveform_right1 readyLatency 0
set_interface_property waveform_right1 ENABLED true

add_interface_port waveform_right1 asi_data_waveform_right1 data Input 16
add_interface_port waveform_right1 asi_valid_waveform_right1 valid Input 1
add_interface_port waveform_right1 asi_ready_waveform_right1 ready Output 1

